name: release-please

# Add permissions at workflow level
permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
      # Only run the following steps if a release was created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      # Add your custom file modification step here
      - name: Update additional file
        if: ${{ steps.release.outputs.release_created }}
        run: |
          # Example: Update version in another file
          echo "Version ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}" > VERSION-ME.txt
          # Add more file modifications as needed

      # Install yq for YAML manipulation
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # Update the version in the CloudFormation template
      # This command uses yq to update the `ComponentVersions.Major.id` field.
      - name: Update template version
        run: |
          yq e -i ".Mappings.ComponentVersions.Major.id = \"${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}\"" template.yaml
        shell: bash
          
      # Commit and push the changes
      - name: Commit changes
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add VERSION-ME.txt
          git add template.yaml
          git commit -m "chore: update VERSION-ME.txt for ${{ steps.release.outputs.tag_name }}"
          git push
